import { FrankRuntimeExecutionParams, StructuredToolExecutionResult } from '../frank-execution-runtime';

export type TaskPriority = 'HIGH' | 'MEDIUM' | 'LOW';

export type TaskStatus =
    | 'QUEUED'
    | 'RUNNING'
    | 'COMPLETED'
    | 'FAILED'
    | 'CANCELLED'
    | 'REJECTED';

export interface SchedulerConfig {
    /** Maximum number of concurrently executing tasks across all tenants */
    maxGlobalConcurrency: number;
    /** Maximum number of concurrently executing tasks for a single tenant */
    maxTenantConcurrency: number;
    /** Maximum total tasks allowed in queue across all tenants */
    maxGlobalQueueSize: number;
    /** Maximum total tasks allowed in queue for a single tenant */
    maxTenantQueueSize: number;
    /** Optional timeout (ms) after which a queued task expires if not started */
    taskQueueTimeoutMs?: number;
    /** Interval in ms after which queued tasks gain priority boost (aging to prevent starvation) */
    agingIntervalMs?: number;
    /** Amount by which effective priority increases per aging interval */
    agingBoostAmount?: number;
}

export interface ScheduleTaskParams<TInput = unknown> {
    /** Tenant identifier resolved from authenticated server session */
    tenantId: string;
    /** Unique task ID (autogenerated if not supplied) */
    taskId?: string;
    /** Optional human readable label/title */
    title?: string;
    /** Task priority level (default: 'MEDIUM') */
    priority?: TaskPriority;
    /** Name of the registered Frank tool to execute */
    toolName: string;
    /** Input payload for the tool */
    input: TInput;
    /** Execution context options passed directly to FrankExecutionRuntime */
    executionParams?: Omit<FrankRuntimeExecutionParams, 'tenantId' | 'toolName' | 'input'>;
    /** Optional external AbortSignal for task cancellation */
    abortSignal?: AbortSignal;
}

export interface TaskHandle<TOutput = unknown> {
    taskId: string;
    tenantId: string;
    toolName: string;
    priority: TaskPriority;
    get status(): TaskStatus;
    promise: Promise<StructuredToolExecutionResult<TOutput>>;
    cancel: (reason?: string) => boolean;
    abortSignal: AbortSignal;
}

export interface TaskMetrics {
    queuedCount: number;
    activeCount: number;
    completedCount: number;
    failedCount: number;
    cancelledCount: number;
    rejectedCount: number;
}

export interface SchedulerSnapshot {
    activeGlobalCount: number;
    queuedGlobalCount: number;
    config: SchedulerConfig;
    tenantMetrics: Record<string, TaskMetrics>;
    queuedTasksSummary: Array<{
        taskId: string;
        tenantId: string;
        toolName: string;
        priority: TaskPriority;
        effectivePriority: number;
        enqueuedAt: string;
        waitedMs: number;
    }>;
    runningTasksSummary: Array<{
        taskId: string;
        tenantId: string;
        toolName: string;
        startedAt: string;
        durationMs: number;
    }>;
}
