export enum FunnelStage {
  FLOW_STARTED = 'FLOW_STARTED',
  INTENT_DETECTED = 'INTENT_DETECTED',
  ASKED_CEP = 'ASKED_CEP',
  CEP_PROVIDED = 'CEP_PROVIDED',
  QUANTITY_PROVIDED = 'QUANTITY_PROVIDED',
  FREIGHT_QUOTED = 'FREIGHT_QUOTED',
  FLOW_ABORTED = 'FLOW_ABORTED',
}
