import {
    Activity,
    BarChart3,
    Boxes,
    BrainCircuit,
    Calendar,
    DollarSign,
    FileText,
    LayoutDashboard,
    Map,
    MessageSquare,
    Package,
    Settings2,
    Truck,
    Users,
} from 'lucide-react';
import type { Module, Role } from '@/ui/auth/entitlements-logic';

export type RouteDefinition = {
    pattern: string;
    title: string;
    guard?: {
        roles?: Role[];
        plan?: 'free' | 'pro' | 'domine' | null;
    };
};

export type ModuleConfig = {
    id: string;
    label: string;
    group: string;
    icon: any;
    route: string;
    authModule: Module;
    requiredRoles?: Role[];
    requiredPlan?: 'free' | 'pro' | 'domine' | null;
    navVisible: boolean;
    isPlaceholder?: boolean;
    navGroup?: 'Core' | 'Operacao' | 'Inteligencia' | 'Governanca';
    navOrder?: number;
    summary?: string;
    routes: RouteDefinition[];
};

const FOUNDATION_MODULES: ModuleConfig[] = [
    {
        id: 'cockpit',
        label: 'Cockpit',
        group: 'Workspace',
        icon: LayoutDashboard,
        route: '/cockpit',
        authModule: 'cockpit',
        navVisible: true,
        navGroup: 'Core',
        navOrder: 10,
        summary: 'Visao executiva, alertas e pulso operacional do tenant.',
        routes: [
            { pattern: '/cockpit', title: 'Cockpit' },
            { pattern: '/home', title: 'Cockpit' },
        ],
    },
    {
        id: 'operacao',
        label: 'Operacao',
        group: 'Workspace',
        icon: Activity,
        route: '/operacao',
        authModule: 'operation',
        requiredRoles: ['admin', 'manager', 'operator'],
        navVisible: true,
        navGroup: 'Governanca',
        navOrder: 110,
        summary: 'Fila, capacidade, riscos e pontos de intervencao manual.',
        routes: [
            { pattern: '/operacao', title: 'Operacao' },
            { pattern: '/operacao/fila', title: 'Fila Operacional' },
        ],
    },
    {
        id: 'conversas',
        label: 'Conversas',
        group: 'Operacao Comercial',
        icon: MessageSquare,
        route: '/cockpit/atendimento',
        authModule: 'operation',
        requiredRoles: ['admin', 'manager', 'operator'],
        navVisible: true,
        navGroup: 'Core',
        navOrder: 20,
        summary: 'Inbox operacional com fila densa, thread ativa e contexto lateral do cliente.',
        routes: [
            { pattern: '/cockpit/atendimento', title: 'Atendimento' },
            { pattern: '/cockpit/atendimento/:id', title: 'Conversa' },
        ],
    },
    {
        id: 'clientes',
        label: 'Clientes',
        group: 'Operacao Comercial',
        icon: Users,
        route: '/clientes',
        authModule: 'operation',
        requiredRoles: ['admin', 'manager', 'operator'],
        navVisible: true,
        navGroup: 'Core',
        navOrder: 50,
        summary: 'Cliente 360 com relacionamento, pedidos, simulacoes e acoes operacionais.',
        routes: [
            { pattern: '/clientes', title: 'Clientes' },
        ],
    },
    {
        id: 'pedidos',
        label: 'Pedidos',
        group: 'Operacao Comercial',
        icon: FileText,
        route: '/cockpit/orders',
        authModule: 'operation',
        requiredRoles: ['admin', 'manager', 'operator'],
        navVisible: true,
        navGroup: 'Core',
        navOrder: 30,
        summary: 'Fluxo operacional canonico do pedido com triagem, detalhe, cliente e logistica.',
        routes: [
            { pattern: '/cockpit/orders', title: 'Pedidos' },
            { pattern: '/cockpit/orders/:id', title: 'Detalhes do Pedido' },
        ],
    },
    {
        id: 'logistica',
        label: 'Logistica',
        group: 'Operacao Comercial',
        icon: Truck,
        route: '/logistica',
        authModule: 'frete',
        requiredRoles: ['admin', 'manager', 'operator'],
        navVisible: true,
        navGroup: 'Core',
        navOrder: 40,
        summary: 'Central logistica com fila de acompanhamento, simulacoes, SLA, excecoes e acoes operacionais.',
        routes: [
            { pattern: '/logistica', title: 'Logistica' },
            { pattern: '/logistica/simulador', title: 'Simulador de Frete' },
            { pattern: '/logistica/envios', title: 'Envios' },
            { pattern: '/logistica/rastreamento', title: 'Rastreamento' },
            { pattern: '/logistica/insights', title: 'Insights Logisticos' },
            { pattern: '/freight/simulations', title: 'Simulacoes de Frete' },
            { pattern: '/freight/simulations/:id', title: 'Simulacao de Frete' },
        ],
    },
    {
        id: 'frank',
        label: 'Frank',
        group: 'Inteligencia',
        icon: BrainCircuit,
        route: '/frank',
        authModule: 'cockpit',
        requiredRoles: ['admin', 'manager'],
        navVisible: true,
        navGroup: 'Inteligencia',
        navOrder: 70,
        summary: 'Agente operacional com intencoes, desempenho e trilha de acoes.',
        routes: [
            { pattern: '/frank', title: 'Frank' },
            { pattern: '/cockpit/frank/knowledge', title: 'Knowledge Base' },
            { pattern: '/cockpit/frank/suggestions', title: 'Sugestoes' },
        ],
    },
    {
        id: 'metricas',
        label: 'Metricas',
        group: 'Inteligencia',
        icon: BarChart3,
        route: '/metricas',
        authModule: 'cockpit',
        navVisible: true,
        navGroup: 'Inteligencia',
        navOrder: 80,
        summary: 'Leitura executiva de funil, atendimento, logistica e atribuicao.',
        routes: [
            { pattern: '/metricas', title: 'Metricas' },
            { pattern: '/attribution', title: 'Atribuicao' },
        ],
    },
    {
        id: 'tenant',
        label: 'Tenant',
        group: 'Governanca',
        icon: Boxes,
        route: '/tenant',
        authModule: 'admin',
        requiredRoles: ['admin', 'manager'],
        navVisible: true,
        navGroup: 'Governanca',
        navOrder: 90,
        summary: 'Identidade do tenant, canais, branding e status operacional.',
        routes: [{ pattern: '/tenant', title: 'Tenant' }],
    },
    {
        id: 'configuracoes',
        label: 'Configuracoes',
        group: 'Governanca',
        icon: Settings2,
        route: '/configuracoes',
        authModule: 'settings',
        requiredRoles: ['admin', 'manager'],
        navVisible: true,
        navGroup: 'Governanca',
        navOrder: 100,
        summary: 'Usuarios, permissoes, integracoes, AI provider e auditoria.',
        routes: [{ pattern: '/configuracoes', title: 'Configuracoes' }],
    },
];

const LEGACY_MODULES: ModuleConfig[] = [
    {
        id: 'analytics',
        label: 'Analytics',
        group: 'Legacy',
        icon: BarChart3,
        route: '/cockpit/analytics',
        authModule: 'cockpit',
        navVisible: false,
        routes: [{ pattern: '/cockpit/analytics', title: 'Analytics' }],
    },
    {
        id: 'audit',
        label: 'Audit Logs',
        group: 'Legacy',
        icon: FileText,
        route: '/cockpit/audit',
        authModule: 'audit',
        requiredRoles: ['admin', 'manager', 'operator'],
        navVisible: false,
        routes: [{ pattern: '/cockpit/audit', title: 'Auditoria' }],
    },
    {
        id: 'acquisition',
        label: 'Acquisition',
        group: 'Legacy',
        icon: Activity,
        route: '/cockpit/acquisition',
        authModule: 'acquisition',
        navVisible: false,
        routes: [
            { pattern: '/cockpit/acquisition', title: 'Acquisition' },
            { pattern: '/cockpit/acquisition/activation', title: 'Activation' },
            { pattern: '/cockpit/acquisition/drilldown', title: 'Drilldown de Acquisition' },
        ],
    },
    {
        id: 'freight-hub',
        label: 'Freight Hub',
        group: 'Legacy',
        icon: Truck,
        route: '/painel-logistico',
        authModule: 'frete',
        requiredRoles: ['admin', 'manager'],
        navVisible: false,
        routes: [{ pattern: '/painel-logistico', title: 'Painel Logistico' }],
    },
    {
        id: 'packing-profiles',
        label: 'Perfis de Embalagem',
        group: 'Legacy',
        icon: Package,
        route: '/cockpit/packing-profiles',
        authModule: 'frete',
        requiredRoles: ['admin', 'manager'],
        navVisible: false,
        routes: [{ pattern: '/cockpit/packing-profiles', title: 'Perfis de Embalagem' }],
    },
    {
        id: 'carrier-tables',
        label: 'Tabelas de Frete',
        group: 'Legacy',
        icon: Truck,
        route: '/cockpit/carrier-tables',
        authModule: 'frete',
        requiredRoles: ['admin', 'manager'],
        navVisible: false,
        routes: [
            { pattern: '/cockpit/carrier-tables', title: 'Tabelas de Frete' },
            { pattern: '/logistica/tabelas-frete', title: 'Tabelas de Frete' },
            { pattern: '/logistica/tabelas-frete/:carrier', title: 'Tabela da Transportadora' },
        ],
    },
    {
        id: 'deliveries',
        label: 'Entregas',
        group: 'Legacy',
        icon: Truck,
        route: '/cockpit/deliveries',
        authModule: 'dispatch',
        requiredRoles: ['admin', 'manager'],
        navVisible: false,
        routes: [{ pattern: '/cockpit/deliveries', title: 'Entregas' }],
    },
    {
        id: 'domine',
        label: 'Domine',
        group: 'Legacy',
        icon: Activity,
        route: '/cockpit/domine',
        authModule: 'cockpit',
        requiredRoles: ['admin'],
        navVisible: false,
        routes: [
            { pattern: '/cockpit/domine', title: 'Domine' },
            { pattern: '/cockpit/domine/dlq', title: 'DLQ Domine' },
            { pattern: '/cockpit/domine/health', title: 'Health Domine' },
        ],
    },
    {
        id: 'knowledge',
        label: 'Knowledge',
        group: 'Legacy',
        icon: BrainCircuit,
        route: '/cockpit/knowledge',
        authModule: 'cockpit',
        navVisible: false,
        routes: [
            { pattern: '/cockpit/knowledge', title: 'KNOWLEDGE BASE' },
            { pattern: '/cockpit/knowledge/collections', title: 'Colecoes' },
            { pattern: '/cockpit/knowledge/ask', title: 'Frank Ask' },
            { pattern: '/cockpit/knowledge/documents/:docId/versions/:versionId/chunks/:chunkId', title: 'Chunk Viewer' },
        ],
    },
    {
        id: 'equipe',
        label: 'Equipe',
        group: 'Legacy',
        icon: Users,
        route: '/cockpit/equipe',
        authModule: 'admin',
        requiredRoles: ['admin', 'manager'],
        navVisible: false,
        routes: [{ pattern: '/cockpit/equipe', title: 'Equipe' }],
    },
    {
        id: 'rate-limit',
        label: 'Rate Limit',
        group: 'Legacy',
        icon: Activity,
        route: '/cockpit/rate-limit',
        authModule: 'admin',
        requiredRoles: ['admin'],
        navVisible: false,
        routes: [{ pattern: '/cockpit/rate-limit', title: 'Rate Limit' }],
    },
    {
        id: 'settings',
        label: 'Configuracoes Tecnicas',
        group: 'Legacy',
        icon: Settings2,
        route: '/settings',
        authModule: 'settings',
        requiredRoles: ['admin'],
        navVisible: false,
        routes: [{ pattern: '/settings', title: 'Configuracoes Tecnicas' }],
    },
    {
        id: 'finance',
        label: 'Financeiro',
        group: 'Legacy',
        icon: DollarSign,
        route: '/cockpit/finance',
        authModule: 'admin',
        requiredRoles: ['admin'],
        navVisible: false,
        isPlaceholder: true,
        routes: [{ pattern: '/cockpit/finance', title: 'Financeiro' }],
    },
    {
        id: 'tenants',
        label: 'Tenants',
        group: 'Legacy',
        icon: Boxes,
        route: '/cockpit/tenants',
        authModule: 'admin',
        requiredRoles: ['admin'],
        navVisible: false,
        isPlaceholder: true,
        routes: [{ pattern: '/cockpit/tenants', title: 'Tenants' }],
    },
    {
        id: 'dispatch',
        label: 'Dispatch',
        group: 'Legacy',
        icon: Package,
        route: '/modules/dispatch',
        authModule: 'dispatch',
        requiredRoles: ['admin', 'manager', 'operator'],
        requiredPlan: 'pro',
        navVisible: false,
        isPlaceholder: true,
        routes: [{ pattern: '/modules/dispatch', title: 'Dispatch' }],
    },
    {
        id: 'technicians',
        label: 'Tecnicos',
        group: 'Legacy',
        icon: Users,
        route: '/modules/technicians',
        authModule: 'operation',
        requiredRoles: ['admin', 'manager', 'operator'],
        requiredPlan: 'pro',
        navVisible: false,
        isPlaceholder: true,
        routes: [
            { pattern: '/modules/technicians', title: 'Tecnicos' },
            { pattern: '/modules/technicians/:id', title: 'Perfil do Tecnico' },
        ],
    },
    {
        id: 'routes',
        label: 'Rotas',
        group: 'Legacy',
        icon: Map,
        route: '/modules/routes',
        authModule: 'operation',
        requiredRoles: ['admin', 'manager', 'operator'],
        requiredPlan: 'pro',
        navVisible: false,
        isPlaceholder: true,
        routes: [
            { pattern: '/modules/routes', title: 'Rotas' },
            { pattern: '/modules/routes/:id', title: 'Detalhes da Rota' },
        ],
    },
    {
        id: 'events',
        label: 'Eventos Logisticos',
        group: 'Legacy',
        icon: Calendar,
        route: '/modules/events',
        authModule: 'operation',
        requiredRoles: ['admin', 'manager', 'operator', 'viewer'],
        requiredPlan: 'pro',
        navVisible: false,
        isPlaceholder: true,
        routes: [{ pattern: '/modules/events', title: 'Eventos Logisticos' }],
    },
    {
        id: 'sales-legacy',
        label: 'Vendas',
        group: 'Legacy',
        icon: FileText,
        route: '/vendas/cotacao',
        authModule: 'operation',
        requiredRoles: ['admin', 'manager', 'operator'],
        navVisible: false,
        routes: [{ pattern: '/vendas/cotacao', title: 'Cotacao' }],
    },
    {
        id: 'financeiro-legacy',
        label: 'Financeiro',
        group: 'Legacy',
        icon: DollarSign,
        route: '/financeiro/frete',
        authModule: 'cockpit',
        navVisible: false,
        routes: [
            { pattern: '/financeiro/frete', title: 'Custos de Frete' },
            { pattern: '/financeiro/margem', title: 'Margem' },
        ],
    },
    {
        id: 'sistema-legacy',
        label: 'Sistema',
        group: 'Legacy',
        icon: Activity,
        route: '/sistema/health',
        authModule: 'admin',
        requiredRoles: ['admin'],
        navVisible: false,
        routes: [
            { pattern: '/sistema/health', title: 'Health' },
            { pattern: '/sistema/dlq', title: 'DLQ' },
            { pattern: '/sistema/logs', title: 'Logs' },
            { pattern: '/sistema/security', title: 'Security' },
        ],
    },
    {
        id: 'supreme-legacy',
        label: 'Supreme',
        group: 'Legacy',
        icon: BrainCircuit,
        route: '/supreme',
        authModule: 'admin',
        requiredRoles: ['admin'],
        navVisible: false,
        routes: [{ pattern: '/supreme', title: 'Supreme' }],
    },
    {
        id: 'cockpit-legacy',
        label: 'Cockpit Legacy',
        group: 'Legacy',
        icon: LayoutDashboard,
        route: '/cockpit',
        authModule: 'cockpit',
        navVisible: false,
        routes: [
            { pattern: '/cockpit/:area', title: 'Cockpit' },
            { pattern: '/cockpit/:area/:subarea', title: 'Cockpit' },
            { pattern: '/cockpit/:area/:subarea/:item', title: 'Cockpit' },
            { pattern: '/cockpit/:area/:subarea/:item/:detail', title: 'Cockpit' },
        ],
    },
];

export const MODULES: ModuleConfig[] = [...FOUNDATION_MODULES, ...LEGACY_MODULES];

const PRIMARY_NAV_GROUP_ORDER: Array<NonNullable<ModuleConfig['navGroup']>> = ['Core', 'Operacao', 'Inteligencia', 'Governanca'];

export function getPrimaryNavigationModules() {
    return [...FOUNDATION_MODULES].sort((left, right) => (left.navOrder ?? 0) - (right.navOrder ?? 0));
}

export function getPrimaryNavigationGroups() {
    return PRIMARY_NAV_GROUP_ORDER.map((groupKey) => ({
        key: groupKey,
        title:
            groupKey === 'Core'
                ? 'Cockpit Lojacond'
                : groupKey === 'Operacao'
                  ? 'Operacao'
                  : groupKey === 'Inteligencia'
                    ? 'Inteligencia'
                    : 'Governanca',
        items: getPrimaryNavigationModules().filter((moduleItem) => moduleItem.navGroup === groupKey),
    })).filter((group) => group.items.length > 0);
}
