// ---------------------------------------------------------------------------
// Concierge Types — foundational contracts for the CONDSTORE OS concierge
// decision engine. Pure data types, no logic.
// ---------------------------------------------------------------------------

/** Supported concierge intents. */
export type ConciergeIntent = 'cotacao_simulada' | 'pedido' | 'suporte';

/** Field-level validation and minimisation rules for an intent. */
export interface ConciergeFieldRule {
    required: readonly string[];
    forbidden: readonly string[];
    ttlHours: number;
    requiresTenant: boolean;
}

/** Validated context produced by the context builder. */
export interface ConciergeContext {
    intent: ConciergeIntent;
    tenantId?: string;
    sessionId?: string;
    createdAt: Date;
    fields: Record<string, unknown>;
}

/** A single option generated by the option engine. */
export interface ConciergeOption {
    id: string;
    price: number;
    deadlineDays: number;
    score: number;
}

/** Final recommendation produced by the recommendation engine. */
export interface ConciergeRecommendation {
    bestOptionId: string;
    explanation: string;
    tradeoff?: string;
}
