import fs from 'fs';
import path from 'path';

// Define the root for the App Router
const APP_DIR = path.join(process.cwd(), 'src', 'app');
const OUTPUT_FILE = path.join(process.cwd(), 'docs', '_generated', 'routes-inventory.md');

// Helper to recursively find routes
function findRoutes(dir: string, baseRoute: string = ''): string[] {
    let routes: string[] = [];
    if (!fs.existsSync(dir)) return routes;

    const files = fs.readdirSync(dir);

    for (const file of files) {
        // Exclude specific Next.js internal/build folders or UI co-located folders if necessary
        if (file.startsWith('_') || file === 'components' || file === 'ui' || file === 'lib') continue;

        const fullPath = path.join(dir, file);
        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
            // Check for route groups e.g. (app) or (public)
            const isRouteGroup = file.startsWith('(') && file.endsWith(')');
            const nextBaseRoute = isRouteGroup ? baseRoute : `${baseRoute}/${file}`;

            routes = routes.concat(findRoutes(fullPath, nextBaseRoute));
        } else {
            // Check if it's a page or route file
            if (file === 'page.tsx' || file === 'page.ts' || file === 'route.ts') {
                // If it's the root page/route, keep '/'
                const finalRoute = baseRoute === '' ? '/' : baseRoute;
                routes.push(finalRoute);
            }
        }
    }

    return Array.from(new Set(routes)).sort();
}

function generateInventory() {
    console.log('🔍 Scanning src/app for routes...');
    const routes = findRoutes(APP_DIR);

    console.log(`✅ Detected ${routes.length} routes.`);

    // Generate Markdown
    const mdLines = [
        '# Auto-Generated Routes Inventory',
        '',
        '> This file is auto-generated by `npm run routes:inventory`. Do not edit manually.',
        '',
        '| Detected Path | Type |',
        '|---|---|',
    ];

    routes.forEach(route => {
        const type = route.startsWith('/api') ? 'API' : 'Page';
        mdLines.push(`| \`${route}\` | ${type} |`);
    });

    // Ensure _generated dir exists
    const outDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
    }

    fs.writeFileSync(OUTPUT_FILE, mdLines.join('\n'));
    console.log(`📄 Wrote inventory to docs/_generated/routes-inventory.md`);
}

generateInventory();
