import {
  githubUrl,
  type ArchEdge,
  type ArchFlow,
  type ArchMeta,
  type ArchNode,
  type EdgeType,
  type Layer,
  type NodeKind,
  type NodeStatus,
} from "./types";

// Full catalog is large. This commit lands the structure;
// the complete audited inventory from earth-beam-arrow-plum is maintained
// in the source repo and will be synced here.
// For a working explorer, NODES / EDGES / FLOWS / META must be present.

export const META: ArchMeta = {
  product: "CONDSTORE OS",
  repo: "catcaio/projeto-condstore",
  repoUrl: "https://github.com/catcaio/projeto-condstore",
  homepage: "https://app.condstoreos.com",
  auditedAt: "2026-09-15",
  sourceOfTruth: "GitHub repository code (priority over docs)",
  stack: {
    frontend: "Next.js 16 + React 19",
    backend: "Next.js App Router / Route Handlers",
    database: "MySQL / TiDB + Drizzle ORM",
    cache: "Redis (ioredis)",
    ai: "OpenAI-compatible (Frank)",
    messaging: "Twilio WhatsApp",
    payments: "Stripe",
    logistics: "Melhor Envio",
  },
  counts: {
    modules: 37,
    apiRoutes: 120,
    pages: 130,
    tables: 100,
  },
};

const D: Array<{
  id: string;
  name: string;
  kind: NodeKind;
  domain: string;
  parent: string | null;
  status: NodeStatus;
  mvp: boolean;
  layer: Layer;
  path?: string;
  desc: string;
  evidence: string;
  does?: string[];
  files?: string[];
  deps?: string[];
  tech?: string[];
  tags?: string[];
}> = [
  {
    id: "os",
    name: "CONDSTORE OS",
    kind: "system",
    domain: "os",
    parent: null,
    status: "production",
    mvp: true,
    layer: "product",
    path: "README.md",
    desc: "SaaS multi-tenant Next.js para operação comercial supervisionada via WhatsApp, CRM, cotação de frete, pedidos, logística e Cockpit.",
    evidence: "README.md e ARCHITECTURE.md; package.json name=condstore-os; homepage app.condstoreos.com.",
    does: ["Operação WhatsApp → cotação → pedido → shipment", "Isolamento multi-tenant", "Camada Frank supervisionada"],
    files: ["README.md", "ARCHITECTURE.md", "package.json"],
    tech: ["Next.js 16", "React 19", "TypeScript", "Drizzle", "MySQL/TiDB"],
    tags: ["root"],
  },
  {
    id: "product",
    name: "Produto / Superfícies",
    kind: "domain",
    domain: "product",
    parent: "os",
    status: "production",
    mvp: true,
    layer: "product",
    path: "src/app",
    desc: "App Router: Cockpit autenticado, marketing público, auth, billing, superfícies MVP.",
    evidence: "130 page.tsx em src/app; grupos (app), (auth), (public), (marketing).",
    tags: ["ui"],
  },
  {
    id: "ops",
    name: "Domínio operacional",
    kind: "domain",
    domain: "ops",
    parent: "os",
    status: "production",
    mvp: true,
    layer: "backend",
    path: "src/modules",
    desc: "Casos de uso: atendimento, clientes, CRM, frete, pedidos, logística, cockpit, billing.",
    evidence: "37 pastas em src/modules.",
    tags: ["domain"],
  },
  {
    id: "ai",
    name: "IA / Frank",
    kind: "domain",
    domain: "ai",
    parent: "os",
    status: "partial",
    mvp: false,
    layer: "ai",
    path: "src/modules/frank",
    desc: "Agente operacional supervisionado. Runtime desligado no MVP (FRANK_RUNTIME_ENABLED=false).",
    evidence: "src/config/app.config.ts; docs/mvp/boundaries.md.",
    tags: ["frank"],
  },
  {
    id: "data",
    name: "Dados",
    kind: "domain",
    domain: "data",
    parent: "os",
    status: "production",
    mvp: true,
    layer: "database",
    path: "src/drizzle/schema.ts",
    desc: "Modelo físico Drizzle/MySQL. Schema único, ~100 tabelas.",
    evidence: "src/drizzle/schema.ts; migrações drizzle/0000–0082.",
    tags: ["schema"],
  },
  {
    id: "events",
    name: "Eventos e filas",
    kind: "domain",
    domain: "events",
    parent: "os",
    status: "implemented",
    mvp: true,
    layer: "events",
    path: "src/lib/events",
    desc: "Operational Event Bus + DOMINE (idempotency, async, DLQ).",
    evidence: "src/lib/events; src/modules/domine.",
    tags: ["async"],
  },
  {
    id: "integrations",
    name: "Integrações",
    kind: "domain",
    domain: "integrations",
    parent: "os",
    status: "production",
    mvp: true,
    layer: "integration",
    path: "package.json",
    desc: "Twilio, Stripe, Melhor Envio, LLM, Qdrant, Redis, MySQL, S3, Google OAuth, SMTP, Sentry.",
    evidence: "package.json + adapters em src/modules e src/infra.",
    tags: ["external"],
  },
  {
    id: "infra",
    name: "Infraestrutura",
    kind: "domain",
    domain: "infra",
    parent: "os",
    status: "production",
    mvp: true,
    layer: "infra",
    path: "src/infra",
    desc: "Auth, DB, Redis, jobs, rate-limit, observabilidade, workers, CI/CD Vercel.",
    evidence: "src/infra/* ; .github/workflows ; vercel.json.",
    tags: ["platform"],
  },
  {
    id: "security",
    name: "Segurança e tenancy",
    kind: "domain",
    domain: "security",
    parent: "os",
    status: "production",
    mvp: true,
    layer: "security",
    path: "src/infra/auth",
    desc: "JWT cookie, RBAC, guards, isolamento por tenantId, PII AES-GCM.",
    evidence: "src/infra/auth; src/middleware.ts; src/infra/pii/crypto.ts.",
    tags: ["rbac", "tenant"],
  },
  {
    id: "quality",
    name: "Qualidade e governança",
    kind: "domain",
    domain: "quality",
    parent: "os",
    status: "implemented",
    mvp: true,
    layer: "tests",
    path: "scripts",
    desc: "Gates de CI: env leak, routes:sync, typecheck, lint, coverage, build, mvp-freeze.",
    evidence: "package.json scripts + .github/workflows.",
    tags: ["ci"],
  },
  {
    id: "stack",
    name: "Stack técnica",
    kind: "domain",
    domain: "stack",
    parent: "os",
    status: "production",
    mvp: true,
    layer: "infra",
    path: "package.json",
    desc: "Tecnologias extraídas de package.json e configs reais.",
    evidence: "package.json dependencies.",
    tags: ["tech"],
  },
  {
    id: "cockpit-ui",
    name: "Cockpit",
    kind: "page",
    domain: "product",
    parent: "product",
    status: "production",
    mvp: true,
    layer: "frontend",
    path: "src/app/(app)/cockpit",
    desc: "Superfície operacional canônica. Rota /cockpit.",
    evidence: "README: rota canônica /cockpit.",
    deps: ["middleware"],
    tags: ["cockpit"],
  },
  {
    id: "atendimento",
    name: "Atendimento",
    kind: "module",
    domain: "ops",
    parent: "ops",
    status: "production",
    mvp: true,
    layer: "backend",
    path: "src/modules/atendimento",
    desc: "Conversas WhatsApp, assign/release, cotação embutida.",
    evidence: "src/modules/atendimento + APIs /api/cockpit/conversations.",
  },
  {
    id: "orders",
    name: "Orders",
    kind: "module",
    domain: "ops",
    parent: "ops",
    status: "production",
    mvp: true,
    layer: "backend",
    path: "src/modules/orders",
    desc: "Ciclo de vida de pedidos.",
    evidence: "src/modules/orders + cockpit/orders.",
  },
  {
    id: "freight",
    name: "Freight",
    kind: "module",
    domain: "ops",
    parent: "ops",
    status: "production",
    mvp: true,
    layer: "backend",
    path: "src/modules/freight",
    desc: "Cotação e rating de frete (Melhor Envio e tabelas).",
    evidence: "src/modules/freight.",
  },
  {
    id: "logistics",
    name: "Logistics / Shipments",
    kind: "module",
    domain: "ops",
    parent: "ops",
    status: "production",
    mvp: true,
    layer: "backend",
    path: "src/modules/logistics",
    desc: "Shipments e vínculo com pedidos.",
    evidence: "src/modules/logistics + fulfillment consolidation PRs.",
  },
  {
    id: "frank-service",
    name: "Frank Service",
    kind: "service",
    domain: "ai",
    parent: "ai",
    status: "partial",
    mvp: false,
    layer: "ai",
    path: "src/modules/frank",
    desc: "Runtime do agente (tools, memória, RAG). Desligado no MVP.",
    evidence: "FRANK_RUNTIME_ENABLED=false.",
  },
  {
    id: "middleware",
    name: "Auth Middleware",
    kind: "security",
    domain: "security",
    parent: "security",
    status: "production",
    mvp: true,
    layer: "security",
    path: "src/middleware.ts",
    desc: "Injeta x-auth-tenant-id e protege rotas do cockpit.",
    evidence: "src/middleware.ts.",
  },
  {
    id: "twilio",
    name: "Twilio WhatsApp",
    kind: "integration",
    domain: "integrations",
    parent: "integrations",
    status: "production",
    mvp: true,
    layer: "integration",
    path: "src/server/twilio",
    desc: "Webhook e envio de mensagens WhatsApp.",
    evidence: "src/server/twilio + /api/whatsapp/incoming.",
  },
  {
    id: "stripe",
    name: "Stripe",
    kind: "integration",
    domain: "integrations",
    parent: "integrations",
    status: "implemented",
    mvp: false,
    layer: "integration",
    path: "src/core/stripe",
    desc: "Checkout e webhooks de assinatura.",
    evidence: "/api/webhook/stripe; billing pages.",
  },
  {
    id: "melhor-envio",
    name: "Melhor Envio",
    kind: "integration",
    domain: "integrations",
    parent: "integrations",
    status: "production",
    mvp: true,
    layer: "integration",
    path: "src/modules/freight",
    desc: "Carrier adapter para cotação e etiquetas.",
    evidence: "adapters em freight.",
  },
];

function buildNodes(defs: typeof D): ArchNode[] {
  return defs.map((d) => ({
    id: d.id,
    name: d.name,
    kind: d.kind,
    domain: d.domain,
    status: d.status,
    path: d.path,
    description: d.desc,
    responsibilities: d.does ?? [],
    dependencies: d.deps ?? [],
    relatedFiles: d.files ?? [],
    github: d.path ? githubUrl(d.path) : undefined,
    evidence: d.evidence,
    technologies: d.tech ?? [],
    mvp: d.mvp,
    tags: d.tags ?? [],
    parentId: d.parent,
    layer: d.layer,
  }));
}

export const NODES: ArchNode[] = buildNodes(D);

export const EDGES: ArchEdge[] = [
  { id: "e-os-product", source: "os", target: "product", type: "contains" },
  { id: "e-os-ops", source: "os", target: "ops", type: "contains" },
  { id: "e-os-ai", source: "os", target: "ai", type: "contains" },
  { id: "e-os-data", source: "os", target: "data", type: "contains" },
  { id: "e-os-events", source: "os", target: "events", type: "contains" },
  { id: "e-os-int", source: "os", target: "integrations", type: "contains" },
  { id: "e-os-infra", source: "os", target: "infra", type: "contains" },
  { id: "e-os-sec", source: "os", target: "security", type: "contains" },
  { id: "e-os-q", source: "os", target: "quality", type: "contains" },
  { id: "e-os-stack", source: "os", target: "stack", type: "contains" },
  { id: "e-product-cockpit", source: "product", target: "cockpit-ui", type: "contains" },
  { id: "e-ops-atend", source: "ops", target: "atendimento", type: "contains" },
  { id: "e-ops-orders", source: "ops", target: "orders", type: "contains" },
  { id: "e-ops-freight", source: "ops", target: "freight", type: "contains" },
  { id: "e-ops-log", source: "ops", target: "logistics", type: "contains" },
  { id: "e-ai-frank", source: "ai", target: "frank-service", type: "contains" },
  { id: "e-sec-mw", source: "security", target: "middleware", type: "contains" },
  { id: "e-int-twilio", source: "integrations", target: "twilio", type: "contains" },
  { id: "e-int-stripe", source: "integrations", target: "stripe", type: "contains" },
  { id: "e-int-me", source: "integrations", target: "melhor-envio", type: "contains" },
  { id: "e-atend-twilio", source: "atendimento", target: "twilio", type: "integrates" },
  { id: "e-freight-me", source: "freight", target: "melhor-envio", type: "integrates" },
  { id: "e-cockpit-mw", source: "cockpit-ui", target: "middleware", type: "depends" },
];

export const FLOWS: ArchFlow[] = [
  {
    id: "lead-to-delivery",
    name: "Lead → Entrega",
    description: "Fluxo operacional principal: WhatsApp → atendimento → cotação → pedido → shipment.",
    mvp: true,
    steps: [
      { nodeId: "twilio", label: "WhatsApp", detail: "Mensagem chega via Twilio webhook" },
      { nodeId: "atendimento", label: "Atendimento", detail: "Conversa criada / atribuída" },
      { nodeId: "freight", label: "Cotação", detail: "Quote de frete" },
      { nodeId: "orders", label: "Pedido", detail: "Order gerado" },
      { nodeId: "logistics", label: "Shipment", detail: "Envio e rastreio" },
    ],
  },
];

export function childrenOf(id: string): ArchNode[] {
  return NODES.filter((n) => n.parentId === id);
}

export function dependentsOf(id: string): string[] {
  return EDGES.filter((e) => e.target === id || (e.source === id && e.type === "depends")).map((e) =>
    e.target === id ? e.source : e.target,
  );
}
