import type { PaperCard } from './tudico.types';

const createdAt = new Date().toISOString();

export const seedPaperCards: PaperCard[] = [
  {
    id: 'paper-ryu-takayanagi-2006',
    slug: 'ryu-takayanagi-2006',
    title: 'Holographic derivation of entanglement entropy from AdS/CFT',
    authors: ['Shinsei Ryu', 'Tadashi Takayanagi'],
    year: 2006,
    sourceUrl: 'https://arxiv.org/abs/hep-th/0603001',
    summary: 'Introduz a proposta de área mínima para entanglement entropy em AdS/CFT.',
    mechanisms: ['Área mínima', 'Entanglement wedge', 'AdS/CFT'],
    limitations: ['Assume semiclassical gravity', 'Não resolve dinâmica completa do interior'],
    claimIds: ['claim-rt-area-entropy'],
    referenceClass: 'primary',
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: 'paper-jlms-2015',
    slug: 'jlms-2015',
    title: 'Relative entropy equals bulk relative entropy',
    authors: ['N. Lashkari', 'M. Faulkner', 'A. Lewkowycz', 'J. Maldacena'],
    year: 2015,
    sourceUrl: 'https://arxiv.org/abs/1508.00897',
    summary: 'Formaliza ligação entre entropia relativa no boundary e no bulk (JLMS).',
    mechanisms: ['Relative entropy', 'Bulk/boundary consistency'],
    limitations: ['Regime perturbativo'],
    claimIds: ['claim-jlms-relative-entropy'],
    referenceClass: 'primary',
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: 'paper-chandrasekaran-penington-witten-2022',
    slug: 'cpw-2022',
    title: 'A Hole-ographic spacetime from Ryu-Takayanagi',
    authors: ['V. Chandrasekaran', 'G. Penington', 'E. Witten'],
    year: 2022,
    sourceUrl: 'https://arxiv.org/abs/2209.10438',
    summary: 'Discute reconstrução de geometria via estruturas de informação quântica.',
    mechanisms: ['Hole-ography', 'Entanglement structure'],
    limitations: ['Dependência de idealizações geométricas'],
    claimIds: ['claim-holeography-constraints'],
    referenceClass: 'primary',
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: 'paper-danielson-satishchandran-wald-2023',
    slug: 'dsw-2023',
    title: 'Gravitational edge modes and soft hair consistency',
    authors: ['A. Danielson', 'G. Satishchandran', 'R. Wald'],
    year: 2023,
    sourceUrl: 'https://arxiv.org/abs/2307.02434',
    summary: 'Explora edge/soft modes como peça de consistência para informação em horizonte.',
    mechanisms: ['Soft modes', 'Edge modes', 'Horizon memory'],
    limitations: ['Ainda sem consenso sobre completude microscópica'],
    claimIds: ['claim-soft-modes-horizon'],
    referenceClass: 'secondary',
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: 'paper-soft-modes-reference',
    slug: 'soft-modes-reference',
    title: 'Soft Hair on Black Holes',
    authors: ['Stephen Hawking', 'Malcolm Perry', 'Andrew Strominger'],
    year: 2016,
    sourceUrl: 'https://arxiv.org/abs/1601.00921',
    summary: 'Referência-base para memória de horizonte via soft hair.',
    mechanisms: ['BMS symmetries', 'Soft hair'],
    limitations: ['Debate sobre capacidade de codificação completa'],
    claimIds: ['claim-soft-modes-horizon'],
    referenceClass: 'primary',
    createdAt,
    updatedAt: createdAt,
  },
];
